[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

; Required libraries for the parking meter project
lib_deps =
    rocketscream/Low-Power
    makuna/RTC
    GxEPD2
    Adafruit GFX Library
    Adafruit BusIO
